config/routes.rb
GenderGuess::Application.routes.draw do

  root 'static_pages#home'
  match "/guess", to: 'guesser#guess', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  

end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guesser_controller.rb
class GuesserController < ApplicationController
  def guess
    begin
      height = params['height']
      mass = params['mass']
      if height.nil? or mass.nil? or height.empty? or mass.empty?
        render(:file => File.join(Rails.root, 'public/missing.html'), :status => 403, :layout => false)
      else
        height = Integer(height, 10)
        mass = Integer(mass, 10)

        units = params['units']
        if units != 'metric'
          puts "units: " + units
          height, mass = view_context.american_to_metric(height, mass)
        end

        # Record the inputs for future evil purposes
        Query.create(height: height, mass: mass)

        # Eyeball the charts at http://www.amstat.org/publications/jse/v11n2/datasets.johnson.html
        if height < 165
          @gender = 'female'
        elsif height > 177
          @gender = 'male'
        else
          if mass > 70
            @gender = 'male'
          elsif mass < 60
            @gender = 'female'
          else
            # FIXME: Do something smart and scientific here
            g = rand
            @gender = g > 0.5 ? "male" : "female"
          end
        end
      end
    rescue ArgumentError => e
      render(:file => File.join(Rails.root, 'public/corrupt.html'), :status => 403, :layout => false)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Implements the world-famous Paul Irish IE conditional comments HTML tag--in HAML
# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
# Credit: https://gist.github.com/drewbarontini/2225615
def cc_html(options={}, &blk)
  attrs = options.map { |(k, v)| " #{h k}='#{h v}'" }.join('')
  [ "<!--[if lt IE 7]> <html#{attrs} class='lt-ie9 lt-ie8 lt-ie7'> <![endif]-->",
    "<!--[if IE 7]>    <html#{attrs} class='lt-ie9 lt-ie8'> <![endif]-->",
    "<!--[if IE 8]>    <html#{attrs} class='lt-ie9'> <![endif]-->",
    "<!--[if gt IE 8]><!--> <html#{attrs} class=''> <!--<![endif]-->",
    capture_haml(&blk).strip,
    "</html>"
  ].join("\n")
end
def h(str); Rack::Utils.escape_html(str); end

end

app/helpers/guesser_helper.rb
module GuesserHelper
  # These are actually used from the controller. The helpers
  # are meant to be used from the View, which never touches
  # this.
  # TODO: Move this somewhere that makes more sense.

  def inches_to_centimeters(inches)
    # 1 ft  == 0.3048 m == 304.8 cm
    # =>
    inches * 0.254
  end

  def pounds_to_kilos (pounds)
    pounds * 0.4536
  end

  def american_to_metric(height, mass)
    # assumes height is in inches and mass in pounds
    h = inches_to_centimeters height
    m = pounds_to_kilos mass
    # Really should round this, at least
    return h.to_int, m.to_int
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guesser/guess.html.haml
:markdown
  Pigeonholed!
  ============

  This human is obviously #{@gender}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GenderGuess</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
!= cc_html(:lang => 'en') do
  %head
    %meta(charset='UTF-8')

    -# Set viewport width to device width for mobile
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  
    %title= content_for?(:title) ? yield(:title) : "Guess Gender"

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/custom.modernizr" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    %body
      -# Header
      %section.top-bar-section
        %ul.left
          -# %li.divider
          %li
            = link_to image_tag('logo.png', alt: "Gender Guess"), root_path
          -# %li.divider
        %ul.right
          %li
            = link_to "About", about_path
          -# %li.divider
          %li
            = link_to "Help", help_path

      -# "Real" body"
      %div.row
        -# Add some padding for big screens
        %div.large-1.columns
        %div.large-10.small-12.columns
          = yield
        %div.large-1.columns

      -# Footer
      %div.row
        %div.large-6.columns
          &copy; 2013 James Gatannah
        %div.large-6.columns
          = link_to image_tag('agplv3-88x31.png', alt: "AGPL"), "http://www.gnu.org/licenses/agpl.txt"

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>What's Going On?</h1>
<p>I was asked to do a simple sample Ruby on Rails site
as part of a job screening. Part of the instructions included
"Be creative and have fun." So I'm using the excuse to explore
some technologies that have been on back-burner parts of
my todo list for months now.</p>

<p>Odds are, there isn't anything interesting in the site at
all. You certainly shouldn't take its opinions seriously.
The actual web site should never be considered anything more
than an amusement piece.</p>

app/views/static_pages/about.html.haml
- provide(:title, 'About')

:markdown
  What's Going On?
  ================

  I was asked to do a simple sample Ruby on Rails site
  as part of a job screening. Part of the instructions included
  "Be creative and have fun." So I'm using the excuse to explore
  some technologies that have been on back-burner parts of
  my todo list for months now.

  Odds are, there isn't anything interesting in the site at
  all. You certainly shouldn't take its opinions seriously.
  The actual web site should never be considered anything more
  than an amusement piece.

app/views/static_pages/help.html.haml
- provide(:title, 'Help')

:markdown
  How's This Work?
  ================


  Enter a human's body mass and height.

-# How do I do footnotes?
:markdown
  Based on stringent scientific statistical analysis*
  the highly sophisticated AI, which is a gestalt of
  multiple data centers all over the world, will try to
  guess whether that human is physically male or female.

-# Seriously. Footnote.
:markdown
  \* Note: Like most random websites you run across,
  this is complete and utter balderdash. Please do not
  take this seriously.

app/views/static_pages/home.html.haml
-provide(:title, 'Guess Gender')
%h1 Let Us Pigeonhole Someone!

= form_tag('/guess', method: 'get') do
  = label_tag(:height, "Height (centimeters):", id: "height")
  = number_field_tag(:height, 0, min: 1)
  = label_tag(:mass, "Mass (kilograms):", id: "mass")
  = number_field_tag(:mass, 0, min: 1)
  %div.row
    %div.large-1.columns 
      = radio_button_tag(:units, "metric", checked=true, id: "metric_units")
      = label_tag(:units_metric, "Metric")
    %div.large-11.columns
      = radio_button_tag(:units, "American", nil, id: "American_units")
      = label_tag(:units_american, "American")
  = submit_tag("Pigeon Hole", class: "button radius")

:markdown
  Based on the latest scientific advancements in
  phrenology, reflexology, and astrology,
  I'll try to label a human as either male or female.